version: '3.9'

services:
  app:
    build: .
    image: guestbook_app:1.0.0
    env_file: .env
    stdin_open: true
    tty: true
    user: ${UID}:${UID}
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["symfony", "server:start"]
