version: '3.9'

services:
  app:
    build: .
    image: guestbook_app:1.0.0
    stdin_open: true
    tty: true
    user: ${UID}:${UID}
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["symfony", "server:start"]
    depends_on:
      - database

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  ###< doctrine/doctrine-bundle ###

volumes:
  db-data:
